- name: Include Steps for NodeJS
  include_role:
    name: common
    tasks_from: nodejs

- name: Include Steps for Rsyslog
  include_role:
    name: common
    tasks_from: rsyslog

- name: Setup User Service
  template:
    src: user.service
    dest: /etc/systemd/system/user.service

- name: Start User Service
  systemd:
    name: user
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Include Prometheus Role
  include_role:
    name: prometheus

- name: Include Filebeat Role
  include_role:
    name: filebeat
  vars:
    LOG_FILE: /var/log/user.log
    EXCLUDE_LINES: nodejs
    IS_STRUCTURED: true
    APPNAME: user